import { shallowMount } from "@vue/test-utils";
import { describe, expect, it, vi } from "vitest";

const noop = vi.fn();

const dashboardMock = {
  timeframeOptions: [],
  searchQuery: "",
  searchResults: [],
  searchOpen: false,
  watchlistGroups: [],
  userWatchGroups: [],
  marketWatchItems: [],
  activeWatchGroupId: null,
  workspacePresets: [],
  activeWorkspacePresetId: null,
  compareSeries: [],
  comparisonMode: "percent",
  watchlist: [],
  watchlistLoading: false,
  watchlistError: false,
  leftTab: "watch",
  rightTab: "indicators",
  workspaceTab: "chart",
  currentTicker: "AAPL",
  currentName: "Apple",
  currentPeriod: "1y",
  currentInterval: "1d",
  klineDisplayMode: "day",
  cleanChartMode: false,
  chartLayout: "single",
  chartLoading: false,
  loadingMessage: "",
  ohlcData: [],
  drawings: [],
  selectedDrawingId: null,
  alerts: [],
  notifications: [],
  wsConnected: false,
  latency: "0ms",
  lastUpdate: "—",
  clockTime: "—",
  dbStats: null,
  dbStatsError: "",
  institutionalDate: "2026-03-29",
  institutionalData: null,
  institutionalLoading: false,
  institutionalError: "",
  institutionalInsights: null,
  institutionalInsightsLoading: false,
  institutionalInsightsError: "",
  institutionalFuturesCommodity: "",
  institutionalOptionsCommodity: "",
  institutionalHistoryDays: 30,
  syncingCurrent: false,
  syncingAll: false,
  quote: {
    price: null,
    open: null,
    high: null,
    low: null,
    volume: null,
    market_cap: null,
    change: 0,
    change_pct: 0,
    name: "Apple",
  },
  marketStatus: {
    nyseOpen: false,
    nasdaqOpen: false,
    tseOpen: false,
    hkOpen: false,
  },
  activeInd: {},
  activePanels: {},
  indicatorSettings: {},
  activeTool: "cursor",
  crosshair: {
    visible: false,
    absoluteIndex: null,
    canvasX: null,
    canvasY: null,
    hoverPrice: "—",
    change: "—",
    changePct: "—",
    date: "—",
    open: "—",
    high: "—",
    low: "—",
    close: "—",
    volume: "—",
  },
  alertModalOpen: false,
  alertForm: {
    ticker: "AAPL",
    type: "price",
    cond: "大於",
    value: "",
  },
  backtestForm: {
    strategy: "MA 黃金/死亡交叉",
    start: "2022-01-01",
    end: "2026-03-29",
    capital: 100000,
    fee: 0.1,
    sl: 5,
    tp: 10,
  },
  backtestResult: null,
  indicatorSnapshot: {
    techSummaryHtml: "",
  },
  institutionalOverlay: null,
  backendUrl: "http://127.0.0.1:8001",
  searchSymbols: noop,
  closeSearch: noop,
  submitSearch: noop,
  selectSearchResult: noop,
  createWatchGroup: noop,
  renameWatchGroup: noop,
  deleteWatchGroup: noop,
  addTickerToWatchlist: noop,
  removeTickerFromWatchlist: noop,
  reorderWatchlistItems: noop,
  addCompareTicker: noop,
  removeCompareTicker: noop,
  clearCompareTickers: noop,
  setComparisonMode: noop,
  setTimeframe: noop,
  setKlineDisplayMode: noop,
  setLeftTab: noop,
  setActiveWatchGroup: noop,
  setRightTab: noop,
  setWorkspaceTab: noop,
  setInstitutionalDate: noop,
  setInstitutionalFuturesCommodity: noop,
  setInstitutionalOptionsCommodity: noop,
  setInstitutionalHistoryDays: noop,
  shiftInstitutionalDate: noop,
  loadInstitutionalData: noop,
  loadInstitutionalInsights: noop,
  setChartLayout: noop,
  selectTicker: noop,
  toggleIndicator: noop,
  togglePanel: noop,
  updateIndicatorSetting: noop,
  applyIndicatorPreset: noop,
  clearIndicators: noop,
  setTool: noop,
  addSignal: noop,
  clearDrawings: noop,
  addHorizontalLine: noop,
  addDrawing: noop,
  removeLastDrawing: noop,
  selectDrawing: noop,
  removeDrawing: noop,
  updateDrawing: noop,
  toggleDrawingVisibility: noop,
  toggleDrawingLock: noop,
  saveWorkspacePreset: noop,
  loadWorkspacePreset: noop,
  deleteWorkspacePreset: noop,
  updateCrosshair: noop,
  hideCrosshair: noop,
  syncCurrentTicker: noop,
  syncAll: noop,
  dismissNotification: noop,
  openAlertModal: noop,
  closeAlertModal: noop,
  updateAlertField: noop,
  saveAlert: noop,
  updateBacktestField: noop,
  runBacktest: noop,
};

vi.mock("./composables/useDashboard", () => ({
  useDashboard: () => dashboardMock,
}));

import App from "./App.vue";

describe("App", () => {
  it("mounts the application shell", () => {
    const wrapper = shallowMount(App, {
      global: {
        stubs: {
          DashboardTopbar: true,
          WatchlistPanel: true,
          ChartWorkspace: true,
          RightSidebar: true,
          InstitutionalDashboard: true,
          StatusBar: true,
          NotificationPanel: true,
          AlertModal: true,
        },
      },
    });

    expect(wrapper.find(".app-shell").exists()).toBe(true);
  });
});
