import { flushPromises, shallowMount } from "@vue/test-utils";
import { ref } from "vue";
import { describe, expect, it, vi } from "vitest";

const noop = vi.fn();

const dashboardMock = {
  timeframeOptions: [],
  searchQuery: "",
  searchResults: [],
  searchOpen: false,
  watchlistGroups: [],
  userWatchGroups: [],
  marketWatchItems: [],
  activeWatchGroupId: null,
  workspacePresets: [],
  activeWorkspacePresetId: null,
  compareSeries: [],
  comparisonMode: "percent",
  watchlist: [],
  watchlistLoading: false,
  watchlistError: false,
  leftTab: "watch",
  rightTab: "indicators",
  workspaceTab: "chart",
  currentTicker: "AAPL",
  currentName: "Apple",
  currentPeriod: "1y",
  currentInterval: "1d",
  klineDisplayMode: "day",
  cleanChartMode: false,
  chartLayout: "single",
  chartLoading: false,
  loadingMessage: "",
  ohlcData: [],
  drawings: [],
  selectedDrawingId: null,
  alerts: [],
  notifications: [],
  wsConnected: false,
  latency: "0ms",
  lastUpdate: "—",
  clockTime: "—",
  dbStats: null,
  dbStatsLoading: false,
  dbStatsError: "",
  institutionalDate: "2026-03-29",
  institutionalData: null,
  institutionalLoading: false,
  institutionalError: "",
  institutionalInsights: null,
  institutionalInsightsLoading: false,
  institutionalInsightsError: "",
  institutionalFuturesCommodity: "",
  institutionalOptionsCommodity: "",
  institutionalHistoryDays: 30,
  calendarEvents: [],
  tickerEvents: [],
  tickerNews: [],
  macroDashboard: { items: [], summary: {}, snapshot_date: null },
  fundamentalsSummary: null,
  taiwanChipSummary: null,
  screenerFilters: {
    market: "ALL",
    search: "",
    sector: "",
    min_price: "",
    min_volume_ratio: "",
    max_pe_ratio: "",
    min_dividend_yield: "",
    near_52w_high_pct: "",
    upcoming_event_days: "",
    chip_bias: "any",
    ma_alignment: "any",
    sort_by: "score",
    limit: 50,
  },
  screenerResults: { items: [], total: 0, filters: {}, generated_at: null },
  screenerPresets: [],
  screenerLoading: false,
  syncingCurrent: false,
  syncingAll: false,
  quote: {
    price: null,
    open: null,
    high: null,
    low: null,
    volume: null,
    market_cap: null,
    change: 0,
    change_pct: 0,
    name: "Apple",
  },
  marketStatus: {
    nyseOpen: false,
    nasdaqOpen: false,
    tseOpen: false,
    hkOpen: false,
  },
  activeInd: {},
  activePanels: {},
  indicatorSettings: {},
  activeTool: "cursor",
  crosshair: {
    visible: false,
    absoluteIndex: null,
    canvasX: null,
    canvasY: null,
    hoverPrice: "—",
    change: "—",
    changePct: "—",
    date: "—",
    open: "—",
    high: "—",
    low: "—",
    close: "—",
    volume: "—",
  },
  alertModalOpen: false,
  alertForm: {
    ticker: "AAPL",
    type: "price",
    cond: "大於",
    value: "",
  },
  backtestForm: {
    strategy: "MA 黃金/死亡交叉",
    start: "2022-01-01",
    end: "2026-03-29",
    capital: 100000,
    fee: 0.1,
    slippage: 0,
    sl: 5,
    tp: 10,
  },
  backtestResult: null,
  backtestHistory: [],
  backtestLoading: false,
  journalForm: {
    id: null,
    ticker: "AAPL",
    market: "US",
    direction: "long",
    strategy_code: "",
    entry_time: "2026-04-01T09:00",
    entry_price: "",
    exit_time: "",
    exit_price: "",
    size: 1,
    stop_loss: "",
    take_profit: "",
    entry_reason: "",
    exit_reason: "",
    emotion_tag: "",
    review_notes: "",
    tags_text: "",
    attachment_path: "",
    attachment_type: "",
    attachments: [],
  },
  journalEntries: [],
  journalStats: null,
  journalLoading: false,
  journalFilterPresets: [],
  journalFilterScope: "ticker",
  journalFilters: {
    market: "",
    strategy_code: "",
    tag: "",
    search: "",
  },
  indicatorSnapshot: {
    techSummaryHtml: "",
  },
  institutionalOverlay: null,
  backendUrl: "http://127.0.0.1:8001",
  searchSymbols: noop,
  closeSearch: noop,
  submitSearch: noop,
  selectSearchResult: noop,
  createWatchGroup: noop,
  renameWatchGroup: noop,
  deleteWatchGroup: noop,
  addTickerToWatchlist: noop,
  addTickersToWatchlistBatch: noop,
  removeTickerFromWatchlist: noop,
  reorderWatchlistItems: noop,
  addCompareTicker: noop,
  removeCompareTicker: noop,
  clearCompareTickers: noop,
  setComparisonMode: noop,
  setTimeframe: noop,
  setKlineDisplayMode: noop,
  setLeftTab: noop,
  setActiveWatchGroup: noop,
  setRightTab: noop,
  setWorkspaceTab: noop,
  setInstitutionalDate: noop,
  setInstitutionalFuturesCommodity: noop,
  setInstitutionalOptionsCommodity: noop,
  setInstitutionalHistoryDays: noop,
  shiftInstitutionalDate: noop,
  loadInstitutionalData: noop,
  loadInstitutionalInsights: noop,
  loadEventCalendar: noop,
  loadMacroDashboard: noop,
  loadTickerIntelligence: noop,
  setChartLayout: noop,
  selectTicker: noop,
  toggleIndicator: noop,
  togglePanel: noop,
  updateIndicatorSetting: noop,
  applyIndicatorPreset: noop,
  clearIndicators: noop,
  setTool: noop,
  addSignal: noop,
  clearDrawings: noop,
  addHorizontalLine: noop,
  addDrawing: noop,
  removeLastDrawing: noop,
  selectDrawing: noop,
  removeDrawing: noop,
  updateDrawing: noop,
  toggleDrawingVisibility: noop,
  toggleDrawingLock: noop,
  saveWorkspacePreset: noop,
  loadWorkspacePreset: noop,
  deleteWorkspacePreset: noop,
  updateCrosshair: noop,
  hideCrosshair: noop,
  syncCurrentTicker: noop,
  syncAll: noop,
  dismissNotification: noop,
  setNotificationRead: noop,
  openAlertModal: noop,
  closeAlertModal: noop,
  updateAlertField: noop,
  saveAlert: noop,
  deleteAlert: noop,
  updateBacktestField: noop,
  runBacktest: noop,
  selectBacktestRun: noop,
  updateJournalField: noop,
  updateJournalFilter: noop,
  applyJournalFilterPreset: noop,
  saveJournalFilterPreset: noop,
  loadJournalFilterPreset: noop,
  deleteJournalFilterPreset: noop,
  saveJournalEntry: noop,
  deleteJournalEntry: noop,
  selectJournalEntry: noop,
  resetJournalForm: noop,
  addJournalAttachment: noop,
  removeJournalAttachment: noop,
  startJournalEntry: noop,
  updateScreenerFilter: noop,
  runScreener: noop,
  saveScreenerPreset: noop,
  loadScreenerPreset: noop,
  deleteScreenerPreset: noop,
};

vi.mock("./composables/useDashboard", () => ({
  useDashboard: () => dashboardMock,
}));

import App from "./App.vue";

describe("App", () => {
  it("mounts the application shell", () => {
    const wrapper = shallowMount(App, {
      global: {
        stubs: {
          DashboardTopbar: true,
          WatchlistPanel: true,
          ChartWorkspace: true,
          RightSidebar: true,
          InstitutionalDashboard: true,
          EventCenter: true,
          MacroDashboard: true,
          ScreenerWorkspace: true,
          StatusBar: true,
          NotificationPanel: true,
          AlertModal: true,
        },
      },
    });

    expect(wrapper.find(".app-shell").exists()).toBe(true);
  });

  it("creates a dedicated watch group from journal result shortcuts", async () => {
    dashboardMock.userWatchGroups = ref([{ id: 1, name: "警報通知模板 命中池" }]);
    dashboardMock.setLeftTab = vi.fn();
    dashboardMock.createWatchGroup = vi.fn().mockImplementation(async (name) => {
      dashboardMock.userWatchGroups.value = [
        ...dashboardMock.userWatchGroups.value,
        { id: 88, name },
      ];
    });
    dashboardMock.addTickersToWatchlistBatch = vi.fn().mockResolvedValue({ added: 2, failed: 0 });

    const wrapper = shallowMount(App, {
      global: {
        stubs: {
          DashboardTopbar: true,
          WatchlistPanel: true,
          ChartWorkspace: true,
          RightSidebar: {
            name: "RightSidebar",
            template: `
              <button
                data-testid="right-sidebar-trigger"
                @click="$emit('create-watch-group', {
                  name: '警報通知模板 命中池',
                  items: [{ ticker: 'AAPL' }, { ticker: 'MSFT' }],
                })"
              />
            `,
          },
          InstitutionalDashboard: true,
          EventCenter: true,
          MacroDashboard: true,
          ScreenerWorkspace: true,
          StatusBar: true,
          NotificationPanel: true,
          AlertModal: true,
        },
      },
    });

    await wrapper.get('[data-testid="right-sidebar-trigger"]').trigger("click");
    await flushPromises();

    expect(dashboardMock.setLeftTab).toHaveBeenCalledWith("watch");
    expect(dashboardMock.createWatchGroup).toHaveBeenCalledWith("警報通知模板 命中池 (2)");
    expect(dashboardMock.addTickersToWatchlistBatch).toHaveBeenCalledWith(
      [{ ticker: "AAPL" }, { ticker: "MSFT" }],
      88,
    );
  });
});
